/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnvironmentRouteImport } from './routes/environment'
import { Route as HardwareRouteImport } from './routes/hardware'
import { Route as LogRouteImport } from './routes/log'
import { Route as MapRouteImport } from './routes/map'
import { Route as SonarRouteImport } from './routes/sonar'
import { Route as SpectrumRouteImport } from './routes/spectrum'
import { Route as VisionRouteImport } from './routes/vision'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentRoute = EnvironmentRouteImport.update({
  id: '/environment',
  path: '/environment',
  getParentRoute: () => rootRouteImport,
} as any)
const HardwareRoute = HardwareRouteImport.update({
  id: '/hardware',
  path: '/hardware',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const SonarRoute = SonarRouteImport.update({
  id: '/sonar',
  path: '/sonar',
  getParentRoute: () => rootRouteImport,
} as any)
const SpectrumRoute = SpectrumRouteImport.update({
  id: '/spectrum',
  path: '/spectrum',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/environment': typeof EnvironmentRoute
  '/hardware': typeof HardwareRoute
  '/log': typeof LogRoute
  '/map': typeof MapRoute
  '/sonar': typeof SonarRoute
  '/spectrum': typeof SpectrumRoute
  '/vision': typeof VisionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/environment': typeof EnvironmentRoute
  '/hardware': typeof HardwareRoute
  '/log': typeof LogRoute
  '/map': typeof MapRoute
  '/sonar': typeof SonarRoute
  '/spectrum': typeof SpectrumRoute
  '/vision': typeof VisionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/environment': typeof EnvironmentRoute
  '/hardware': typeof HardwareRoute
  '/log': typeof LogRoute
  '/map': typeof MapRoute
  '/sonar': typeof SonarRoute
  '/spectrum': typeof SpectrumRoute
  '/vision': typeof VisionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/environment'
    | '/hardware'
    | '/log'
    | '/map'
    | '/sonar'
    | '/spectrum'
    | '/vision'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/environment'
    | '/hardware'
    | '/log'
    | '/map'
    | '/sonar'
    | '/spectrum'
    | '/vision'
  id:
    | '__root__'
    | '/'
    | '/environment'
    | '/hardware'
    | '/log'
    | '/map'
    | '/sonar'
    | '/spectrum'
    | '/vision'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnvironmentRoute: typeof EnvironmentRoute
  HardwareRoute: typeof HardwareRoute
  LogRoute: typeof LogRoute
  MapRoute: typeof MapRoute
  SonarRoute: typeof SonarRoute
  SpectrumRoute: typeof SpectrumRoute
  VisionRoute: typeof VisionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environment': {
      id: '/environment'
      path: '/environment'
      fullPath: '/environment'
      preLoaderRoute: typeof EnvironmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardware': {
      id: '/hardware'
      path: '/hardware'
      fullPath: '/hardware'
      preLoaderRoute: typeof HardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sonar': {
      id: '/sonar'
      path: '/sonar'
      fullPath: '/sonar'
      preLoaderRoute: typeof SonarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spectrum': {
      id: '/spectrum'
      path: '/spectrum'
      fullPath: '/spectrum'
      preLoaderRoute: typeof SpectrumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnvironmentRoute: EnvironmentRoute,
  HardwareRoute: HardwareRoute,
  LogRoute: LogRoute,
  MapRoute: MapRoute,
  SonarRoute: SonarRoute,
  SpectrumRoute: SpectrumRoute,
  VisionRoute: VisionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
